### ISSUE TITLE
What is the differance between *.core & *.core.shared ?

### ISSUE THREAD

**Issue by HADDADENICAR** [aspnetzero/documents#126]
Following your docs i didn't find a clear explanation on why there are ***.core** and ***.core.shared**
and ***.application** and ***.application.shared** ? 
I can find [here](https://aspnetboilerplate.com/Pages/Documents/Articles/Introduction-With-AspNet-Core-And-Entity-Framework-Core-Part-1/index.html) that you project use ***DDD*** and the role of each project domain (ex: **.core** for entites , **application** for dto ....) but i can't understand the role of .shared projects ?
can you please clarify ?

**Comment by hikalkan** [comment]
application.shared is to separate application service interfaces and DTOs from the application layer implementation. This is needed because we are sharing application service interfaces and DTOs with the Xamarin project. They can also be shared to any client because they are just the contract.

core.shared is a natural result of this separation, because application.shared needed some constants and enums from the domain layer (those are used in DTOs). But we don't want to share our domain with clients. So, we crated core.shared to contain shareable part of the domain layer.

**Comment by hikalkan** [comment]
You can also see roles of the each project in the documentation: https://docs.aspnetzero.com/documents/aspnet-core-mvc/latest/Overview-Core#solution-structure-layers
