### ISSUE TITLE
Phonebook Tutorial. Breaking Changes

### ISSUE THREAD

**Issue by jonassix** [aspnetzero/documents#5]
2 small issues
- You're phone book documentation is made on a older version of aspnetzero/boilerplate. 
- When explaining how the test units work you fail to mention one must change AppTestBase class so the fake database gets seeded with test data

```
            UsingDbContext(context =>
            {
                context.EntityChangeEventHelper = NullEntityChangeEventHelper.Instance;
                context.EventBus = NullEventBus.Instance;

                new TenantRoleAndUserBuilder(context, 1).Create();
                new TestDataBuilder(context, 1).Create();

                //seed persons in PbPersons
                new InitialPeopleCreator(context).Create();
            });
```

**Comment by hikalkan** [comment]
Thank you. We'll check & fix it soon.

**Comment by slaxton** [comment]
It's been more than 2 years and you still haven't updated the PhoneBook documentation

**Comment by ismcagdas** [comment]
@slaxton we didn't face any report related to Phonebook Tutorial after this issue I guess. However, I'm putting this issue to our current work items and we will work on it.

**Comment by alirizaadiyahsi** [comment]
Hi @jonassix, actually you don't need code that you mentioned. We already mentioned like 

> This class (InitialPeopleCreator) is created and called in InitialHostDbBuilder class. 

This is enough to seed data to in-memory test DB. Because `AppTestBase` class depends on EF Core project. So no need to define it in in test project.

And @slaxton, we are updating documents. You can see it from it's GitHub history:
![image](https://user-images.githubusercontent.com/4375000/52993716-38ed7b00-3426-11e9-891b-94e6f9eef81f.png)
